language: android
jdk: oraclejdk7
#env:
#  matrix:
#    - ANDROID_TARGET=android-19  ANDROID_ABI=armeabi-v7a

android:
  components:
    - build-tools-19.1.0
    - android-19
    - sysimg-19
    - extra-android-support
  licenses:
    - android-sdk-license-5be876d5 # new license!
    - android-sdk-license-598b93a6
    - '.*intel.+'
    
install: ./gradlew assemble

script: ./gradlew build
